### ISSUE TITLE
BakkesMod Folder not found + Microsoft .NET Framework error

### ISSUE THREAD

**Issue by GoldenRage** [ItsBranK/BakkesModInjectorCs#1]
Hi,
I just wanted to get your nice work started but it shows this window. 
![BAKKESMOD1](https://user-images.githubusercontent.com/77223753/104116688-2bdc1c80-531b-11eb-89b1-f89594f52966.png)
The Problem is I got Bakkesmod installed and it is working well but in addition this windows keeps openning and nothing is working in the BakkesModInjectorCs (I cant even selcet the bakkesmod folder)
![BAKKESMOD2](https://user-images.githubusercontent.com/77223753/104116689-2c74b300-531b-11eb-8499-b6c3400171d6.png)
(Im sry that the language is german)

**Comment by ItsBranK** [comment]
Yeah ever since Bakkes' changed how the BakkesMod.dll finds paths it broke like everything in my injector, I'm currently in the process of remaking the entire project pretty much. Might take a bit as I am juggling a few different projects atm.

**Comment by ItsBranK** [comment]
Just released an update that fixes this problem along with a lot of other stuff, closing this issue.
